# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [bituniverse, bitshares]
patreon: # Replace with a single Patreon username: bituniverse
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username: bituniverse 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username: bituniverse
issuehunt: # Replace with a single IssueHunt username: bituniverse
otechie: # Replace with a single Otechie username: bituniverse
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['bituniverse.org', 'trade.bituniverse.org', 'exchange.bituniverse.org', 'api.bituniverse.org']
 
